<template>
  <div>
    <section class="main-container document-wrap">
      <p class="p4" style="margin: 0px; text-indent: 24.1px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; line-height: normal; text-align: center;"><span style="font-size: 14pt;"><span style="font-family: SimSong;"><strong>软件使用许可协议</strong></span></span></p>
      <p class="p4" style="margin: 0px; text-indent: 24.1px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;"><strong>一、总则</strong></span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;">本协议是用户(<span class="s1">获得软件授权许可和软件产品的个人或单位，以下简称&ldquo;被许可方&rdquo;</span>)与苏州循迹科技有限公司（以下简称&ldquo;循迹科技&rdquo;）之间关于下载、安装、使用DROME软件及其配套软件产品（以下简称&ldquo;本软件产品&rdquo;）的协议。<span class="s1">除非</span>用户<span class="s1">接受本协议，否则无权下载、安装或使用本软件产品及其相关服务。</span>用户<span class="s1">的安装、使用行为将视为对本协议的接受，并同意接受本协议各项条款的约束。</span></span></p>
      <p class="p4" style="margin: 0px; text-indent: 24.1px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong; margin-top: 12px;"><span style="color: #000000; background-color: #ffffff;"><strong>二、软件产品保护</strong></span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;">1．本软件产品著作权及其它知识产权等相关权利或利益（包括但不限于现已取得或未来可取得的著作权、专利权、<a style="color: #000000; text-decoration: none; background-color: #ffffff;" href="https://www.baidu.com/s?wd=%25E5%2595%2586%25E6%25A0%2587%25E6%259D%2583&amp;tn=44039180_cpr&amp;fenlei=mv6quAkxTZn0IZRqIHckPjm4nH00T1d9uj6sryNhPhD4uWcvuWI-0ZwV5Hcvrjm3rH6sPfKWUMw85HfYnjn4nH6sgvPsT6KdThsqpZwYTjCEQLGCpyw9Uz4Bmy-bIi4WUvYETgN-TLwGUv3EnHm1nW6vnHDz">商标权</a>、商业秘密等）皆为循迹科技所有。</span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;">2．本软件产品受<a style="color: #000000; text-decoration: none; background-color: #ffffff;" href="https://www.baidu.com/s?wd=%25E4%25B8%25AD%25E5%258D%258E%25E4%25BA%25BA%25E6%25B0%2591%25E5%2585%25B1%25E5%2592%258C%25E5%259B%25BD&amp;tn=44039180_cpr&amp;fenlei=mv6quAkxTZn0IZRqIHckPjm4nH00T1d9uj6sryNhPhD4uWcvuWI-0ZwV5Hcvrjm3rH6sPfKWUMw85HfYnjn4nH6sgvPsT6KdThsqpZwYTjCEQLGCpyw9Uz4Bmy-bIi4WUvYETgN-TLwGUv3EnHm1nW6vnHDz">中华人民共和国</a>著作权法等及国际版权条约和其他知识产权法及条约的保护。用户仅获得本软件产品的<a style="color: #000000; text-decoration: none; background-color: #ffffff;" href="https://www.baidu.com/s?wd=%25E9%259D%259E%25E6%258E%2592%25E4%25BB%2596%25E6%2580%25A7&amp;tn=44039180_cpr&amp;fenlei=mv6quAkxTZn0IZRqIHckPjm4nH00T1d9uj6sryNhPhD4uWcvuWI-0ZwV5Hcvrjm3rH6sPfKWUMw85HfYnjn4nH6sgvPsT6KdThsqpZwYTjCEQLGCpyw9Uz4Bmy-bIi4WUvYETgN-TLwGUv3EnHm1nW6vnHDz">非排他性</a>使用权。</span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;">3．未经循迹科技事先书面许可，用户不得实施以下行为：</span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;">（1）复制、发表、出版、披露全部或部分软件内容。</span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;">（2）将许可软件向第三方提供、销售、出租、出借、转让或提供分许可、转许可、通过信息网络传播或以其他形式供他人使用、访问。</span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;">（3）对许可软件进行全部或部分地翻译、分解、反向编译、反汇编、反向工程或其他试图从许可软件导出程序源代码的行为，<span class="s2">或在许可软件的基础上更改、修改、挂接运行或者书写或开发衍生软件、衍生产品或其他软件等。</span></span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;">（4）限制、破坏或绕过许可软件附带的加密附件或乙方提供的其他确保许可软件正确使用的限制性措施。</span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;">（5）将许可软件用于除用户内部使用以外的其他目的，包括但不限于向第三方提供数据处理服务、应用服务、商业共享或其他软件共享安排。</span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;">（6）除掉、掩盖或更改许可软件上有关许可软件著作权或商标的标志等。</span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;">4.被许可方应采取一切合理措施确保未经授权的人员不得访问、复制、出版、披露全部或部分软件内容。</span></p>
      <p class="p6" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong; background-color: #ffffff;"><span style="color: #000000; background-color: #ffffff;">5.本软件产品以现状方式提供，循迹科技不保证本软件产品能够或不能够完全满足用户需求，在用户手册、帮助文件、<a style="color: #000000; text-decoration: none; background-color: #ffffff;" href="https://www.baidu.com/s?wd=%25E4%25BD%25BF%25E7%2594%25A8%25E8%25AF%25B4%25E6%2598%258E%25E4%25B9%25A6&amp;tn=44039180_cpr&amp;fenlei=mv6quAkxTZn0IZRqIHckPjm4nH00T1d9uj6sryNhPhD4uWcvuWI-0ZwV5Hcvrjm3rH6sPfKWUMw85HfYnjn4nH6sgvPsT6KdThsqpZwYTjCEQLGCpyw9Uz4Bmy-bIi4WUvYETgN-TLwGUv3EnHm1nW6vnHDz">使用说明书</a>等<a style="color: #000000; text-decoration: none; background-color: #ffffff;" href="https://www.baidu.com/s?wd=%25E8%25BD%25AF%25E4%25BB%25B6%25E6%2596%2587%25E6%25A1%25A3&amp;tn=44039180_cpr&amp;fenlei=mv6quAkxTZn0IZRqIHckPjm4nH00T1d9uj6sryNhPhD4uWcvuWI-0ZwV5Hcvrjm3rH6sPfKWUMw85HfYnjn4nH6sgvPsT6KdThsqpZwYTjCEQLGCpyw9Uz4Bmy-bIi4WUvYETgN-TLwGUv3EnHm1nW6vnHDz">软件文档</a>中的介绍性内容仅供用户参考，不得理解为对用户所做的任何承诺。循迹科技保留对软件版本进行升级，对功能、内容、结构、界面、运行方式等进行修改或自动更新的权利。</span></p>
      <p class="p7" style="margin: 0px; text-indent: 24.1px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong; background-color: #ffffff; margin-top: 12px;"><span style="color: #000000; background-color: #ffffff;"><strong>三、法律责任与免责</strong></span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span class="s1" style="background-color: #ffffff; color: #000000;">1.使用本软件产品涉及到互联网服务因素，可能会受到各个环节不稳定因素的影响，存在因不可抗力、计算机病毒、黑客攻击、系统不稳定、用户所在位置、用户关机以及其他任何网络、技术、通信线路等原因造成的服务中断或不能满足用户要求的风险，用户须明白并自行承担以上风险。在适用法律允许的最大范围内，循迹科技在任何情况下不就因使用或不能使用本软件产品及所发生的特殊的、意外的、非直接或间接的损失承担赔偿责任，即使用户已事先向循迹科技告知该损害发生的可能性。</span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;">2.<span class="s1">用户违反本协议或相关的服务条款的规定，循迹科技有权视用户的行为性质采取包括但不限于中断使用许可、停止提供服务、限制使用、法律追究等措施。</span></span></p>
      <p class="p6" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong; background-color: #ffffff;"><span style="color: #000000; background-color: #ffffff;">3.用户因第三方如电信部门的通讯线路故障、技术问题、网络、电脑或手故障、系统不稳定性及其他各种不可抗力原因而遭受的经济损失，循迹科技不承担责任<span class="s3">。</span></span></p>
      <p class="p8" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong; color: #343434;"><span style="color: #000000; background-color: #ffffff;"><span class="s1">4．任何情况下，循迹科技支付给被授权人的赔偿均不得超过被授权人最初支付循迹科技的金额。</span><span class="s4"><span class="Apple-converted-space">&nbsp;</span><strong> <span class="Apple-converted-space">&nbsp; </span></strong></span></span></p>
      <p class="p4" style="margin: 0px; text-indent: 24.1px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong; margin-top: 12px;"><span style="color: #000000; background-color: #ffffff;"><strong>四、其他</strong></span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;">1.循迹科技具有对以上各项条款内容的<a style="color: #000000; text-decoration: none; background-color: #ffffff;" href="https://www.baidu.com/s?wd=%25E6%259C%2580%25E7%25BB%2588%25E8%25A7%25A3%25E9%2587%258A%25E6%259D%2583&amp;tn=44039180_cpr&amp;fenlei=mv6quAkxTZn0IZRqIHckPjm4nH00T1d9uj6sryNhPhD4uWcvuWI-0ZwV5Hcvrjm3rH6sPfKWUMw85HfYnjn4nH6sgvPsT6KdThsqpZwYTjCEQLGCpyw9Uz4Bmy-bIi4WUvYETgN-TLwGUv3EnHm1nW6vnHDz">最终解释权</a>和修改权。如用户对循迹科技的解释或修改有异议，应当立即停止使用本软件产品。用户继续使用本软件产品的行为将被视为对循迹科技的解释或修改的接受。</span></p>
      <p class="p5" style="margin: 0px; text-indent: 24px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 12px; line-height: 1.5; font-family: SimSong;"><span style="color: #000000; background-color: #ffffff;">2.因本协议所发生的纠纷，双方同意按照<a style="color: #000000; text-decoration: none; background-color: #ffffff;" href="https://www.baidu.com/s?wd=%25E4%25B8%25AD%25E5%258D%258E%25E4%25BA%25BA%25E6%25B0%2591%25E5%2585%25B1%25E5%2592%258C%25E5%259B%25BD&amp;tn=44039180_cpr&amp;fenlei=mv6quAkxTZn0IZRqIHckPjm4nH00T1d9uj6sryNhPhD4uWcvuWI-0ZwV5Hcvrjm3rH6sPfKWUMw85HfYnjn4nH6sgvPsT6KdThsqpZwYTjCEQLGCpyw9Uz4Bmy-bIi4WUvYETgN-TLwGUv3EnHm1nW6vnHDz">中华人民共和国</a>法律，由循迹科技所在地的有管辖权的法院管辖。 <span class="Apple-converted-space">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span></p>
    </section>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'

onMounted(async () => {})
</script>

<style scoped lang="scss">
.document-wrap {
  padding-top: 60px;
  padding-bottom: 60px;
}
</style>
